version: '3'

services:
    webserver:
        build: .
        ports:
            - 5000:5000
        volumes:
            - .:/app

    database:
        image: postgres:latest
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres